### ISSUE TITLE
"window" is not available during server side rendering.

### ISSUE THREAD

**Issue by PaulieScanlon** [vasturiano/three-geojson-geometry#5]
Hey @vasturiano, sorry, me again 😬

I'm happy to create a PR for this but what are your thoughts on adding a cheeky little `typeof window !== 'undefined' && ...`
check to [https://github.com/vasturiano/three-geojson-geometry/blob/master/src/index.js#L6](https://github.com/vasturiano/three-geojson-geometry/blob/master/src/index.js#L6) so SSR frameworks don't error on build?

**Comment by vasturiano** [comment]
Sounds good. 👍 I left a comment in the PR.
